FROM bcit/alpine:3.11

<%= snippet('labels', binding) -%>

<%= snippet('docker-entrypoint', binding) -%>

<%= snippet('dockerize', binding) -%>

<%= snippet('tini', binding) -%>

RUN apk add --no-cache \
    lua \
    luarocks

RUN ln -s luarocks-5.1 /usr/bin/luarocks

ENTRYPOINT ["/tini", "--", "/docker-entrypoint.sh"]
CMD [ "lua" ]
